### ISSUE TITLE
Find another way to get Kissmanga chapter name

### ISSUE THREAD

**Issue by nhanb** [nhanb/fundoshi#2]
Current code uses the chapter selector dropdown option that's selected, but none of them is selected by default now.

```
▶ python nosetests.py fundoshi.tests.test_kissmanga.TestKissmangaChapter
E..
======================================================================
ERROR: test_middle_chapter (fundoshi.tests.test_kissmanga.TestKissmangaChapter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nhanb/pj/fundoshi/fundoshi/tests/test_kissmanga.py", line 97, in test_middle_chapter
    _test_chapter(self, site, url, expected)
  File "/home/nhanb/pj/fundoshi/fundoshi/tests/__init__.py", line 28, in _test_chapter
    chapter = site.chapter_info(html)
  File "/home/nhanb/pj/fundoshi/fundoshi/sites/kissmanga.py", line 106, in chapter_info
    name = self._chapter_name(soup)
  File "/home/nhanb/pj/fundoshi/fundoshi/sites/kissmanga.py", line 128, in _chapter_name
    return select.find('option', selected=True).text.strip()
AttributeError: 'NoneType' object has no attribute 'text'

----------------------------------------------------------------------
```

**Comment by nhanb** [comment]
Actually, no, they just updated the Naruto chapters with new URLs. Simply changing the test case's URL will work.
